# Generated by Django 5.0.6 on 2024-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tags',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='dima', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
