# Generated by Django 5.0.6 on 2024-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='work_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
