# Generated by Django 5.0.6 on 2024-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
