# Generated by Django 5.0.6 on 2024-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bot_id',
            field=models.CharField(default='default_bot_id', max_length=255),
            preserve_default=False,
        ),
    ]
