# Generated by Django 5.0.6 on 2024-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='user',
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
