# Generated by Django 5.0.6 on 2024-07-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_specialist_user_alter_specialist_description_and_more'),
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar'),
        ),
    ]
